#!/bin/bash
# Reading lines in /etc/fstab

File=/etc/fstab

{
read line1
read line2
} < $File

echo "The first line in $File is:"
echo "$line1"
echo
echo "The second line in $File is:"
echo "$line2"

exit 0
